// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDr2obNivarbk5zobNmU_8Lj8iJI0DrIo',
    appId: '1:70281560599:web:41281c962d976c2cab1252',
    messagingSenderId: '70281560599',
    projectId: 'buyp-9a38b',
    authDomain: 'buyp-9a38b.firebaseapp.com',
    storageBucket: 'buyp-9a38b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr4gXCN6YLgK-oEgXPBZR7VQstRVy9t3c',
    appId: '1:70281560599:android:67c8d1a3295c9f6fab1252',
    messagingSenderId: '70281560599',
    projectId: 'buyp-9a38b',
    storageBucket: 'buyp-9a38b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjbCkgTlaq6Hx-U2fHrbMTpZHVxwUkIjo',
    appId: '1:70281560599:ios:98a66fa3cae0f245ab1252',
    messagingSenderId: '70281560599',
    projectId: 'buyp-9a38b',
    storageBucket: 'buyp-9a38b.appspot.com',
    androidClientId: '70281560599-qj5jcvdopi5ap09mn0g344ir2ki2rlpk.apps.googleusercontent.com',
    iosClientId: '70281560599-h0dqip57an1kco2olqokl81q9glen7b5.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjbCkgTlaq6Hx-U2fHrbMTpZHVxwUkIjo',
    appId: '1:70281560599:ios:98a66fa3cae0f245ab1252',
    messagingSenderId: '70281560599',
    projectId: 'buyp-9a38b',
    storageBucket: 'buyp-9a38b.appspot.com',
    androidClientId: '70281560599-qj5jcvdopi5ap09mn0g344ir2ki2rlpk.apps.googleusercontent.com',
    iosClientId: '70281560599-h0dqip57an1kco2olqokl81q9glen7b5.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecom',
  );
}
